theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.integrate
    - toc.collapse
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

site_name: Ecolink

site_description: Software Documentation of the Ecolink Project

site_author: Cainã Freitas

repo_url: https://github.com/ErasmusEgalitarian/ecolink-docs

plugins:
  - search

nav:
  - Home: index.md
  - Project:
      - Overview: project/overview.md
      - Vision & Objectives:
          - Project Vision: project/vision-objectives/vision.md
          - Project Objectives: project/vision-objectives/objectives.md
      - Stakeholders: project/stakeholders.md
      - Product:
          - Product Overview: project/product/overview.md
          - Product Backlog: project/product/product-backlog-building.md
          - MVPs: project/product/mvp.md
  - Management:
      - Roadmap: project/management/roadmap.md
      - Workflow: project/management/workflow.md
      - Issue Tracking & Task Management: project/management/issue-tracking.md
      - Project Deliverables: project/management/deliverables.md
      - Meeting Minutes: project/management/meetings.md
      - Lessons Learned: project/management/lessons-learned.md
  - Development Process:
      - Software Development Lifecycle: project/development/lifecycle.md
      - Technical Documentation:
          - API Documentation: project/development/technical/api.md
          - System Architecture: project/development/technical/architecture.md
          - Database Schema: project/development/technical/database-schema.md
      - Tools & Dependencies: project/development/tools.md
      - Contributing Policy: project/development/policies.md
  - Setup & Configuration:
      - MkDocs:
          - MkDocs Configuration: setup/mkdocs-configuration.md
          - MkDocs Setup: setup/mkdocs-setup.md
      - Environment Setup:
          - Python Virtual Environment: setup/python-venv-setup.md
          - Publishing Guide: setup/publishing-guide.md
      - README: setup/readme.md
  - References: references.md

extra:
  analytics:
    provider: google
    property: UA-XXXXX-Y

strict: true
use_directory_urls: true
